# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: printing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'printing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprinting.proto\x12\x14\x64istributed_printing\x1a\x1bgoogle/protobuf/empty.proto\"m\n\x0cPrintRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x17\n\x0fmessage_content\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x03\x12\x16\n\x0erequest_number\x18\x04 \x01(\x05\"Y\n\rPrintResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x14\x63onfirmation_message\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x03\"U\n\rAccessRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\x12\x16\n\x0erequest_number\x18\x03 \x01(\x05\"C\n\x0e\x41\x63\x63\x65ssResponse\x12\x16\n\x0e\x61\x63\x63\x65ss_granted\x18\x01 \x01(\x08\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\"U\n\rAccessRelease\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x03\x12\x16\n\x0erequest_number\x18\x03 \x01(\x05\x32k\n\x0fPrintingService\x12X\n\rSendToPrinter\x12\".distributed_printing.PrintRequest\x1a#.distributed_printing.PrintResponse2\xc2\x01\n\x16MutualExclusionService\x12Z\n\rRequestAccess\x12#.distributed_printing.AccessRequest\x1a$.distributed_printing.AccessResponse\x12L\n\rReleaseAccess\x12#.distributed_printing.AccessRelease\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'printing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRINTREQUEST']._serialized_start=69
  _globals['_PRINTREQUEST']._serialized_end=178
  _globals['_PRINTRESPONSE']._serialized_start=180
  _globals['_PRINTRESPONSE']._serialized_end=269
  _globals['_ACCESSREQUEST']._serialized_start=271
  _globals['_ACCESSREQUEST']._serialized_end=356
  _globals['_ACCESSRESPONSE']._serialized_start=358
  _globals['_ACCESSRESPONSE']._serialized_end=425
  _globals['_ACCESSRELEASE']._serialized_start=427
  _globals['_ACCESSRELEASE']._serialized_end=512
  _globals['_PRINTINGSERVICE']._serialized_start=514
  _globals['_PRINTINGSERVICE']._serialized_end=621
  _globals['_MUTUALEXCLUSIONSERVICE']._serialized_start=624
  _globals['_MUTUALEXCLUSIONSERVICE']._serialized_end=818
# @@protoc_insertion_point(module_scope)
